DELETE FROM Tags;
DELETE FROM Meta;

DROP TABLE Tags;
DROP TABLE Meta;


CREATE TABLE IF NOT EXISTS Meta (
  photoID		INT UNSIGNED  	NOT NULL,
  year			INT UNSIGNED	NOT NULL,
  month			INT UNSIGNED	NOT NULL,
  day			INT UNSIGNED	NOT NULL,
  hour			INT UNSIGNED	NOT NULL,
  minute		INT UNSIGNED	NOT NULL,
  second		INT UNSIGNED	NOT NULL,
  location		VARCHAR(30)		NOT NULL,
  PRIMARY KEY  (photoID)
);
CREATE TABLE IF NOT EXISTS Tags (
  photoID		INT UNSIGNED  	NOT NULL,
  tag			VARCHAR(30)		NOT NULL,
  PRIMARY KEY  (photoID,tag),
  FOREIGN KEY  (photoID)  REFERENCES Meta(photoID)
);