DELETE FROM Tags;
DELETE FROM Meta;

DROP TABLE Tags;
DROP TABLE Meta;


CREATE TABLE IF NOT EXISTS Meta (
  photoID		INT UNSIGNED  	NOT NULL,
  year			VARBINARY(100)	NOT NULL,
  month			VARBINARY(100)	NOT NULL,
  day			VARBINARY(100)	NOT NULL,
  hour			VARBINARY(100)	NOT NULL,
  minute		VARBINARY(100)	NOT NULL,
  second		VARBINARY(100)	NOT NULL,
  location		VARBINARY(100)	NOT NULL,
  PRIMARY KEY  (photoID)
);
CREATE TABLE IF NOT EXISTS Tags (
  photoID		INT UNSIGNED  	NOT NULL,
  tag			VARBINARY(100)	NOT NULL,
  PRIMARY KEY  (photoID,tag),
  FOREIGN KEY  (photoID)  REFERENCES Meta(photoID)
);